const articles = [{
  name: 'learn',
  title: 'The Learn Way',
  content: [
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu scelerisque felis imperdiet proin fermentum leo vel. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Vitae elementum curabitur vitae nunc. Eget nullam non nisi est sit amet. Est placerat in egestas erat. Aenean euismod elementum nisi quis. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Magna sit amet purus gravida quis blandit. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Bibendum at varius vel pharetra vel turpis nunc eget. Iaculis nunc sed augue lacus. Cras pulvinar mattis nunc sed blandit.

    Dis parturient montes nascetur ridiculus mus. Quis vel eros donec ac. Ligula ullamcorper malesuada proin libero nunc consequat. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Et malesuada fames ac turpis egestas integer eget. In hac habitasse platea dictumst vestibulum rhoncus est. Consequat semper viverra nam libero justo laoreet sit amet cursus. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Aliquam faucibus purus in massa tempor nec feugiat nisl. Praesent elementum facilisis leo vel fringilla est ullamcorper. Eu mi bibendum neque egestas congue quisque egestas diam.
    
    Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Iaculis at erat pellentesque adipiscing commodo elit. Imperdiet proin fermentum leo vel orci porta non. Felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Bibendum neque egestas congue quisque egestas diam. Proin libero nunc consequat interdum. Aliquet nibh praesent tristique magna sit amet. Purus gravida quis blandit turpis. Semper feugiat nibh sed pulvinar proin gravida. Ac tincidunt vitae semper quis lectus nulla at. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Nisl nisi scelerisque eu ultrices vitae auctor eu augue.
    
    Netus et malesuada fames ac turpis egestas maecenas. Sit amet facilisis magna etiam tempor orci. Libero justo laoreet sit amet cursus sit amet. Potenti nullam ac tortor vitae purus faucibus. Risus ultricies tristique nulla aliquet. Arcu non odio euismod lacinia at quis risus sed vulputate. Etiam sit amet nisl purus. Vulputate ut pharetra sit amet aliquam id diam. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Lacinia quis vel eros donec ac odio tempor orci. Sed lectus vestibulum mattis ullamcorper velit. Massa sapien faucibus et molestie. Dictumst vestibulum rhoncus est pellentesque elit. Sit amet purus gravida quis blandit turpis cursus. Aliquam sem fringilla ut morbi tincidunt augue. Libero nunc consequat interdum varius sit amet. Viverra nibh cras pulvinar mattis nunc sed. Leo vel orci porta non pulvinar neque laoreet. Eget dolor morbi non arcu risus quis varius. Aliquet nec ullamcorper sit amet risus nullam eget felis.
    
    Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Amet purus gravida quis blandit turpis cursus. Ultrices sagittis orci a scelerisque. Augue interdum velit euismod in. At augue eget arcu dictum varius duis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Lorem ipsum dolor sit amet consectetur adipiscing elit. Nibh praesent tristique magna sit amet purus gravida quis blandit. Volutpat est velit egestas dui id ornare arcu odio ut. Augue eget arcu dictum varius duis at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Posuere urna nec tincidunt praesent semper feugiat nibh sed. Mauris cursus mattis molestie a iaculis at erat pellentesque. Imperdiet sed euismod nisi porta lorem mollis aliquam ut.
    `
  ]
}, {
  name: 'fast',
  title: 'The Fastest Way',
  content: [
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu scelerisque felis imperdiet proin fermentum leo vel. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Vitae elementum curabitur vitae nunc. Eget nullam non nisi est sit amet. Est placerat in egestas erat. Aenean euismod elementum nisi quis. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Magna sit amet purus gravida quis blandit. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Bibendum at varius vel pharetra vel turpis nunc eget. Iaculis nunc sed augue lacus. Cras pulvinar mattis nunc sed blandit.

    Dis parturient montes nascetur ridiculus mus. Quis vel eros donec ac. Ligula ullamcorper malesuada proin libero nunc consequat. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Et malesuada fames ac turpis egestas integer eget. In hac habitasse platea dictumst vestibulum rhoncus est. Consequat semper viverra nam libero justo laoreet sit amet cursus. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Aliquam faucibus purus in massa tempor nec feugiat nisl. Praesent elementum facilisis leo vel fringilla est ullamcorper. Eu mi bibendum neque egestas congue quisque egestas diam.
    
    Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Iaculis at erat pellentesque adipiscing commodo elit. Imperdiet proin fermentum leo vel orci porta non. Felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Bibendum neque egestas congue quisque egestas diam. Proin libero nunc consequat interdum. Aliquet nibh praesent tristique magna sit amet. Purus gravida quis blandit turpis. Semper feugiat nibh sed pulvinar proin gravida. Ac tincidunt vitae semper quis lectus nulla at. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Nisl nisi scelerisque eu ultrices vitae auctor eu augue.
    
    Netus et malesuada fames ac turpis egestas maecenas. Sit amet facilisis magna etiam tempor orci. Libero justo laoreet sit amet cursus sit amet. Potenti nullam ac tortor vitae purus faucibus. Risus ultricies tristique nulla aliquet. Arcu non odio euismod lacinia at quis risus sed vulputate. Etiam sit amet nisl purus. Vulputate ut pharetra sit amet aliquam id diam. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Lacinia quis vel eros donec ac odio tempor orci. Sed lectus vestibulum mattis ullamcorper velit. Massa sapien faucibus et molestie. Dictumst vestibulum rhoncus est pellentesque elit. Sit amet purus gravida quis blandit turpis cursus. Aliquam sem fringilla ut morbi tincidunt augue. Libero nunc consequat interdum varius sit amet. Viverra nibh cras pulvinar mattis nunc sed. Leo vel orci porta non pulvinar neque laoreet. Eget dolor morbi non arcu risus quis varius. Aliquet nec ullamcorper sit amet risus nullam eget felis.
    
    Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Amet purus gravida quis blandit turpis cursus. Ultrices sagittis orci a scelerisque. Augue interdum velit euismod in. At augue eget arcu dictum varius duis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Lorem ipsum dolor sit amet consectetur adipiscing elit. Nibh praesent tristique magna sit amet purus gravida quis blandit. Volutpat est velit egestas dui id ornare arcu odio ut. Augue eget arcu dictum varius duis at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Posuere urna nec tincidunt praesent semper feugiat nibh sed. Mauris cursus mattis molestie a iaculis at erat pellentesque. Imperdiet sed euismod nisi porta lorem mollis aliquam ut.`
  ]
}, {
  name: 'quick',
  title: 'The Quick Way',
  content: [
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu scelerisque felis imperdiet proin fermentum leo vel. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Vitae elementum curabitur vitae nunc. Eget nullam non nisi est sit amet. Est placerat in egestas erat. Aenean euismod elementum nisi quis. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Magna sit amet purus gravida quis blandit. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Bibendum at varius vel pharetra vel turpis nunc eget. Iaculis nunc sed augue lacus. Cras pulvinar mattis nunc sed blandit.

    Dis parturient montes nascetur ridiculus mus. Quis vel eros donec ac. Ligula ullamcorper malesuada proin libero nunc consequat. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Et malesuada fames ac turpis egestas integer eget. In hac habitasse platea dictumst vestibulum rhoncus est. Consequat semper viverra nam libero justo laoreet sit amet cursus. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Aliquam faucibus purus in massa tempor nec feugiat nisl. Praesent elementum facilisis leo vel fringilla est ullamcorper. Eu mi bibendum neque egestas congue quisque egestas diam.
    
    Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Iaculis at erat pellentesque adipiscing commodo elit. Imperdiet proin fermentum leo vel orci porta non. Felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Bibendum neque egestas congue quisque egestas diam. Proin libero nunc consequat interdum. Aliquet nibh praesent tristique magna sit amet. Purus gravida quis blandit turpis. Semper feugiat nibh sed pulvinar proin gravida. Ac tincidunt vitae semper quis lectus nulla at. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Nisl nisi scelerisque eu ultrices vitae auctor eu augue.
    
    Netus et malesuada fames ac turpis egestas maecenas. Sit amet facilisis magna etiam tempor orci. Libero justo laoreet sit amet cursus sit amet. Potenti nullam ac tortor vitae purus faucibus. Risus ultricies tristique nulla aliquet. Arcu non odio euismod lacinia at quis risus sed vulputate. Etiam sit amet nisl purus. Vulputate ut pharetra sit amet aliquam id diam. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Lacinia quis vel eros donec ac odio tempor orci. Sed lectus vestibulum mattis ullamcorper velit. Massa sapien faucibus et molestie. Dictumst vestibulum rhoncus est pellentesque elit. Sit amet purus gravida quis blandit turpis cursus. Aliquam sem fringilla ut morbi tincidunt augue. Libero nunc consequat interdum varius sit amet. Viverra nibh cras pulvinar mattis nunc sed. Leo vel orci porta non pulvinar neque laoreet. Eget dolor morbi non arcu risus quis varius. Aliquet nec ullamcorper sit amet risus nullam eget felis.
    
    Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Amet purus gravida quis blandit turpis cursus. Ultrices sagittis orci a scelerisque. Augue interdum velit euismod in. At augue eget arcu dictum varius duis. Adipiscing bibendum est ultricies integer quis auctor elit sed. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Lorem ipsum dolor sit amet consectetur adipiscing elit. Nibh praesent tristique magna sit amet purus gravida quis blandit. Volutpat est velit egestas dui id ornare arcu odio ut. Augue eget arcu dictum varius duis at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Posuere urna nec tincidunt praesent semper feugiat nibh sed. Mauris cursus mattis molestie a iaculis at erat pellentesque. Imperdiet sed euismod nisi porta lorem mollis aliquam ut.`
  ]
}];

export default articles;